spring:
  output:
    ansi:
      enabled: always
  profiles:
    active:
      - local
    group:
      local:
        - oauth-local
        - database-local
        - security-local
        - log-local
      build:
        - oauth-build
        - database-build
        - security-build
        - log-build
      dev:
        - oauth-dev
        - database-dev
        - security-dev
        - log-dev
      prd:
        - oauth-prd
        - database-prd
        - security-prd
        - log-prd
    include:
      - database
      - oauth
      - security
logging:
  config: classpath:log4j2.yml
