spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${asd}
            client-secret: ${dsa}
            scope:
              - email
              - profile
