version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

executors:
  exc:
    docker:
      - image: cimg/openjdk:17.0.7
    resource_class: medium

workflows:
  checkout-and-build:
    jobs:
      - gradle/run:
          executor: exc
