name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1.4.4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: deliver application.properties
        run: echo "${{ secrets.APPLICATION_BUILD }}" > ./src/main/resources/application.yml
        shell: bash

      - name: Copy wallet files from S3
        run: aws s3 cp ${{ secrets.OCI_DATABASE_WALLET }}

      - name: Unzip wallet files
        run: unzip wallet.zip

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set artifact
        run: echo "artifact=$(ls ./build/libs/*.jar)" >> $GITHUB_ENV
