name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: zhulik/redis-action@1.1.0
        with:
          redis version: '5'
          number of databases: 100

      - name: gradle caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Copy wallet files from S3
        run: |
          aws s3 cp s3://aws-server-build/dev-oci-database-wallet.zip .
          aws s3 cp s3://aws-server-build/application-database.yml ./src/main/resources
          aws s3 cp s3://aws-server-build/application-oauth.yml ./src/main/resources
          aws s3 cp s3://aws-server-build/application-security.yml ./src/main/resources

      - name: Unzip wallet files
        run: unzip dev-oci-database-wallet.zip

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set artifact
        run: echo "artifact=$(ls ./build/libs/*.jar)" >> $GITHUB_ENV
