name: CI/CD

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: '5'
          number of databases: 100

      - name: gradle caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: copy wallet file and yml files
        run: |
          aws s3 cp s3://aws-server-build/dev-oci-database-wallet.zip .
          rm ./src/main/resources/application.yml
          aws s3 cp s3://aws-server-build/application.yml ./src/main/resources
          aws s3 cp s3://aws-server-build/application-database.yml ./src/main/resources
          aws s3 cp s3://aws-server-build/application-oauth.yml ./src/main/resources
          aws s3 cp s3://aws-server-build/application-security.yml ./src/main/resources

      - name: unzip wallet files
        run: unzip dev-oci-database-wallet.zip

      - name: build project
        run: ./gradlew clean build

      - name: create deploy zip
        run: |
          mkdir deploy
          mkdir deploy/wallet
          cp ./docker/docker-compose.blue.yml ./deploy/
          cp ./docker/docker-compose.green.yml ./deploy/
          cp ./appspec.yml ./deploy/
          cp ./docker/Dockerfile ./deploy/
          cp ./scripts/*.sh ./deploy/
          cp ./build/libs/*.jar ./deploy/
          cp -r ./Wallet_JCLNMMNRL6DRLP31 ./deploy/wallet/
          zip -r -qq -j ./spring-build.zip ./deploy

      - name: upload project to s3
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          ./spring-build.zip s3://aws-server-build

      - name: create deploy group
        run: aws deploy create-deployment --application-name dev-aws-code_deploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name dev-aws-deploy
          --s3-location bucket=aws-server-build,bundleType=zip,key=spring-build.zip
